### ISSUE TITLE
Roadmaps and Milestones ☂️ 

### ISSUE THREAD

**Issue by shatanikmahanty** [OpenCodeyard/ocyclient#26]
> This is an umbrella issue. To start working on this choose one of the issues from feature set and ask to be assigned

Roadmaps and milestones will be a new enhancement to the OCY website

Feature Set

- [ ] Roadmap page to specify various roadmaps
- [ ] We need to make a customisable page that can show roadmap based on dynamic data from backend
- [ ] Ability to create custom roadmaps from data stored in firebase
- [ ] Each custom roadmap will add a new tab to the roadmap page
- [ ] Initial roadmaps will include: Devlopment Roadmap and Community Roadmap

Blockers:

- [ ] Roadmap UI
